ENV_RUN := conda run -n admix
PIP_RUN := ${cr} pip

.PHONY: help \
	setup \
	create_env \
	install_hooks \
	install_requirements \
	lint_staged \
	lint_all \
	clean \
	unzip_model

help:
	@echo
	@echo "Admixture Makefile"
	@echo
	@echo "Usage:"
	@echo
	@echo "ENVIRONMENT MANAGEMENT"
	@echo
	@echo "\t setup		    creates and sets up the conda environment: "\
							 "installs packages from environment.yml, "\
							 "requirements.txt and installs git commit hooks."
	@echo
	@echo "\t clean  		  Cleans autogenerated files like cache"
	@echo
	@echo "\t unzip_model           Unzips the admixture model used by our algorithm.
	@echo
	@echo "LINTING"
	@echo
	@echo "\t lint_staged	 lints files staged for commit"
	@echo
	@echo "\t lint_all		 lints all files"
	@echo

## MANAGING THE ENVIRONMENT
setup:
	@echo Setting up the repo
	$(MAKE) create_env
	${ENV_RUN} $(MAKE) install_module
	${ENV_RUN} $(MAKE) install_hooks

unzip_model:
	@echo Unziping model file admixture/models/1000Genomes_pop.txt.zip
	@unzip admixture/models/1000Genomes_pop.txt.zip -d admixture/models

create_env:
	@echo Creating environment from environment.yml
	@conda env create -f environment.yml

install_hooks:
	@echo Installing precommit hooks...
	@pre-commit install
	@pre-commit install --hook-type commit-msg

install_module:
	@echo Installing Admixture module...
	@pip install -e .

clean:
	@echo Cleaning files...
	@rm -rf .mypy_cache *.egg_info

## LINTERS
lint_staged:
	@echo Running hook with staged files
	@pre-commit run

lint_all:
	@echo Running hook on all files
	@pre-commit run --all-files

