[tool.black]
line-length="88"

[tool.isort]
length_sort = "True"
multi_line_output="3"
include_trailing_comma="True"
force_grid_wrap="0"
use_parentheses="True"
line_length="88"
known_third_party = ["gitlint", "setuptools"]
known_first_party = []
import_heading_stdlib = "Imports: standard library"
import_heading_firstparty = "Imports: first party"
import_heading_thirdparty = "Imports: third party"

[tool.pylint.'MESSAGES CONTROL']
disable="missing-module-docstring, missing-function-docstring, too-few-public-methods, too-many-arguments, too-many-locals, too-many-instance-attributes, too-many-ancestors, fixme, logging-fstring-interpolation, protected-access, ungrouped-imports, too-many-statements"

[tool.pylint.'SIMILARITIES']
min-similarity-lines="10"
ignore-comments="yes"
ignore-docstrings="yes"
ignore-imports="yes"

[tool.pylint.'BASIC']
argument-rgx="([a-z0-9_]{2,30})$"     # snake_case
variable-rgx="([a-z0-9_]{2,30})$"     # snake_case
const-rgx="([^\\W\\da-z][^\\Wa-z]*|__.*__|name)$"  # UPPER_CASE + name

[tool.pylint.'FORMAT']
max-line-length="88"
